# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-11 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0003_auto_20171111_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='topic',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
