# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0004_auto_20171111_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='tags',
            field=models.TextField(blank=True),
        ),
    ]
