# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0005_topic_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='task',
            name='stage',
        ),
        migrations.AddField(
            model_name='article',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='v1.Topic'),
        ),
        migrations.AddField(
            model_name='task',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='v1.Topic'),
        ),
    ]
