# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0007_auto_20171121_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='tags',
        ),
        migrations.AddField(
            model_name='topic',
            name='tags',
            field=models.TextField(blank=True),
        ),
    ]
