# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-02 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0009_auto_20171121_0105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='github_username',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='twitter_username',
        ),
    ]
